//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int productId { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public int existencia { get; set; }
        public Nullable<int> codcat { get; set; }
    
        public virtual categorias categoria { get; set; }
    }
}
